# Generated by Django 3.0.7 on 2020-06-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_noticias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticias',
            options={'verbose_name': 'noticias', 'verbose_name_plural': 'noticias'},
        ),
        migrations.AlterModelOptions(
            name='rutinas',
            options={'verbose_name': 'rutina', 'verbose_name_plural': 'rutinas'},
        ),
        migrations.AlterField(
            model_name='comentario',
            name='info',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='rutinas',
            name='info',
            field=models.TextField(max_length=500),
        ),
    ]
