# Generated by Django 3.0.7 on 2020-06-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200620_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='info',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='rutinas',
            name='info',
            field=models.CharField(max_length=500),
        ),
    ]
